#!/bin/bash

filename="null"
compiler="gcc"
cachedir=".hq9c/cache"
bottleno="99"
verbosity="false"
debugging="false"

while getopts i:o:c:h:b:v:d flag
do
	case "${flag}" in
		i) filename=${OPTARG};;
		o) output=${OPTARG};;
		c) compiler=${OPTARG};;
		b) bottleno=${OPTARG};;
		v) verbosity=${OPTARG};;
		d) debugging=${OPTARG};;
		*) ;;
	esac
done

if [ -f "$filename" ]; then
	echo "File given exists"
fi

if [ "$compiler" = "rust" ] || [ "$compiler" = "gcc" ] || [ "$compiler" = "clang" ]; then
	echo "Compiler is compatible"
else
	echo "Compiler isn't compatible, use gcc, rust or clang, default is gcc."
fi

if [ "$verbosity" = "true" ]; then
	echo "Verbosity enabled"
fi

if [ "$debugging" = "true" ]; then
	echo "Debug enabled"
fi

# Execute the C executable.
if [ ! -f "./compile" ]; then
	echo "Running 'make'"
	cd .. && make
fi
./compiler "$filename" "$output" "$compiler" "$bottleno" "$verbosity" "$debugging"